version: "3.1"
services:
  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    links:
      - php-fpm
    volumes:
      - ../:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ../:/var/www/app
    depends_on:
      - db

  db:
    image: "postgres"
    environment:
      POSTGRES_DB: airplane_app_db
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433
    volumes:
      - airplane-app-db-data:/var/lib/postgresql/data/

volumes:
  airplane-app-db-data:

